repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.3.7
    hooks:
      # Run the linter and sort imports
      - id: ruff
        args: [ --fix, --select, I]
      # Run the formatter
      - id: ruff-format
