version: "3.8"

services:
  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes: 
      - ${QDRANT_STORAGE_DIR:-/data/postgres}:/var/lib/postgresql/data


