version: "3.8"

services:
  app:
    image: ${CI_REGISTRY_IMAGE}/embeddings:${CI_EMBEDDINGS_IMAGE_TAG}
    restart: always
    command: python3 app.py --models-dir /models --hf-repo-id ${EMBEDDINGS_HF_REPO_ID} ${FORCE_DOWNLOAD} ${DEBUG} --host 0.0.0.0 --port 8000
    volumes:
      - ${MODELS_DIR}:/models
    ports:
      - ${EMBEDDINGS_PORT}:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

