version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    restart: always
    environment:
        discovery.type: single-node
        xpack.security.enabled: false
        ES_JAVA_OPTS: "-Xms2g -Xmx2g"
        ELASTIC_USERNAME: elastic
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    ports:
      - ${ELASTIC_PORT}:9200
    volumes:
      - elasticsearch:/var/lib/elasticsearch/data
  qdrant:
    image: qdrant/qdrant:v1.5.0
    restart: always
    ports:
      - ${QDRANT_REST_PORT}:6333
      - ${QDRANT_GRPC_PORT}:6334
    volumes:
      - qdrant:/qdrant/storage
  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes: 
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  qdrant:
  elasticsearch:
