default:
  before_script:
    - | # export env file and copy routing table to pyalbert config
      if [[ -z $CI_ENVIRONMENT_NAME ]]; then
        echo "info: CI_ENVIRONMENT_NAME is empty, skip the export"

      else
        if [[ $CI_COMMIT_BRANCH = "staging" ]]; then
          echo "info: export staging env file of $CI_ENVIRONMENT_NAME environment"
          export $(grep -v "^#" $STAGING__ENV_FILE | xargs)
          cp $STAGING__ENV_FILE ./.env
          echo "info: copy staging routing table to pyalbert config"

        elif [[ $CI_COMMIT_BRANCH = "main" ]]; then
          echo "info: export production env file of $CI_ENVIRONMENT_NAME environment"
          export $(grep -v "^#" $PROD__ENV_FILE | xargs)
          cp $PROD__ENV_FILE ./.env
          echo "info: copy production routing table to pyalbert config"
        fi

        cp $LLM_ROUTING_TABLE ./llm_routing_table.json

        echo "POSTGRES_HOST=${CI_DEPLOY_HOST}" >> ./.env
        echo "QDRANT_HOST=${CI_DEPLOY_HOST}" >> ./.env
        echo "ELASTIC_HOST=${CI_DEPLOY_HOST}" >> ./.env
        echo "EMBEDDINGS_HOST=${CI_DEPLOY_HOST}" >> ./.env
      fi
